name: Build Flet APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        id: build
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          runner-python-version: "3.13"
          bundled-python-version: "3.13"
          build-number: ${{ github.run_number }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: ${{ steps.build.outputs.archive }}
